#!/usr/bin/python3
def uniq_add(my_list=[]):
    add = set((my_list))
    j = 0
    for i in add:
        j+= i
    return (j)
my_list = [1, 2, 3, 1, 4, 2, 5]
result = uniq_add(my_list)
print("Result: {:d}".format(result))
