#!/usr/bin/python3
def multiple_returns(sentence):
    new_tup = ""
    #tup = (("Length: {:d} - First character: {}".format(len(sentence, sentence[0])))
    tup = (len(sentence), sentence[0])
    """
    for i in tup:
        print(i, end="")
    print(type(tup))
    return new_tup
    """
    return (tup)

sentence = "2t school, I      learnt C!"
length, first = multiple_returns(sentence)
print("Length: {:d} - First character: {}".format(length, first))
#print(multiple_returns("lilian is a girl"))
